# Generated by Django 3.1.6 on 2021-02-20 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boss_list', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='boss_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boss_list.bosslist'),
            preserve_default=False,
        ),
    ]
