# Generated by Django 3.1.6 on 2021-02-21 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boss_list', '0002_bosslist_secret_key'),
        ('players', '0002_player_boss_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='boss_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='boss_list.bosslist'),
        ),
    ]
